# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1  #使用官方脚本创建java环境
        with:
          java-version: 1.8

      - name: config  prod file
        run: |
          mv src/main/resources/application-dev.yml src/main/resources/application.yml
          cat src/main/resources/application.yml
          sed -i "9 s/123456/${{ secrets.DB_PWD }}/" src/main/resources/application.yml
#          sed -i "s/127.0.0.1/$DBIP/g" src/main/resources/application.yml

      - name: Build with Maven
        run: sh mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V



      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: 'target/'
          remote_path: '/opt/zz/'
          args: '-o ConnectTimeout=5'

      - name: start project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/zz/ && sh /opt/zz/travisAuto.sh start

